/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ColorGeneratorLazyImport = createFileRoute('/color-generator')()
const ColorExamplesLazyImport = createFileRoute('/color-examples')()
const ColorDemoLazyImport = createFileRoute('/color-demo')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ColorGeneratorLazyRoute = ColorGeneratorLazyImport.update({
  path: '/color-generator',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/color-generator.lazy').then((d) => d.Route),
)

const ColorExamplesLazyRoute = ColorExamplesLazyImport.update({
  path: '/color-examples',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/color-examples.lazy').then((d) => d.Route),
)

const ColorDemoLazyRoute = ColorDemoLazyImport.update({
  path: '/color-demo',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/color-demo.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/color-demo': {
      preLoaderRoute: typeof ColorDemoLazyImport
      parentRoute: typeof rootRoute
    }
    '/color-examples': {
      preLoaderRoute: typeof ColorExamplesLazyImport
      parentRoute: typeof rootRoute
    }
    '/color-generator': {
      preLoaderRoute: typeof ColorGeneratorLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ColorDemoLazyRoute,
  ColorExamplesLazyRoute,
  ColorGeneratorLazyRoute,
])

/* prettier-ignore-end */
